### ISSUE TITLE
出现一个九宫格里四个8的情况

### ISSUE THREAD

**Issue by JianhaoLu** [myth984/sudoku#4]
![image](https://user-images.githubusercontent.com/25343841/105455594-b844f280-5cbe-11eb-94f8-2b7306024ba1.png)

**Comment by myth984** [comment]
真是人心难测 有人用了我的appId 改了后台数据 生成了错误的棋盘

**Comment by ld7942** [comment]
低估了网友的破坏力

**Comment by Qbsstg** [comment]
已经变成聊天室了，大家太会玩了

**Comment by JianhaoLu** [comment]
10都出来了，被网友玩坏了，hhhh

**Comment by john-june** [comment]
兄弟,这一波人心难测我没想到的

**Comment by xrfinbupt** [comment]
要知道 善良的人总比邪恶的人多，希望你不要失去信心

**Comment by qimy0521** [comment]
真人心不古

**Comment by zhukunzg** [comment]
看评论笑翻了

**Comment by shenchunhang** [comment]
现在不能用了吗?

**Comment by myth984** [comment]
> 现在不能用了吗?

是的

**Comment by ydPro-G** [comment]
怪不得打不开了

**Comment by SpiritQAQ** [comment]
摸鱼不够还要搞破坏，坏得很

**Comment by SimonAKing** [comment]
hahahaha 人心不古
